### ISSUE TITLE
How to blur the select placeholder div after choose?

### ISSUE THREAD

**Issue by amerllica** [chenjiahan/relect#2]
In [demo page](http://chenjiahan.github.io/relect/) the first option, "Jon Snow", after I choose it, the select placeholder div, still focus, how I blur it after change?

**Comment by amerllica** [comment]
I asked same question in @jesWatson `react select` component, His solution was `autoBlur`.
[this](https://github.com/JedWatson/react-select/issues/1763) is my question link. but this doesn't work in your component.

**Comment by chenjiahan** [comment]
Hi, @amerllica, Sorry to tell you that Relect doesn't support autoBlur prop yet,  I will add this prop later.

**Comment by amerllica** [comment]
Thanks Dear @chenjiahan
It's so important for me, please guide me, I wanna add it by myself. I wanna use it in my project.

**Comment by chenjiahan** [comment]
@amerllica autoBlur prop has been added in version 1.1.0.

**Comment by amerllica** [comment]
Hi dear @chenjiahan
I add this prop by myself, but thank you for your kind.
